server:
  port: 9500


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.130.20.137:3306/fire-monitor?SetTimezone=CTS
      username: user1
      password: fireworkz0518A6400_
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    group:
      ordersystem:
        mapper: debug

#powerjob:
#  worker:
#    akka-port: 27777
#    app-name: fire-monitor
#    server-address: 116.205.107.104:7700
#    protocol: http
#    store-strategy: disk
#    max-result-length: 4096
#    max-appended-wf-context-length: 4096
#    max-lightweight-task-num: 1024
#    max-heavy-task-num: 64
#  server-address:
