server:
  port: 9500


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.130.20.137:3306/monitor-fire?SetTimezone=CTS
      username: user1
      password: fireworkz0518A6400_

logging:
  level:
    group:
      ordersystem:
        mapper: debug
