server:
  port: 9500


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.130.20.137:3306/fire-monitor?SetTimezone=CTS
      username: user1
      password: fireworkz0518A6400_
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    group:
      ordersystem:
        mapper: debug
